version: "3.9"
services:
  mariadb:
    build:
      args:
        ALPINE_VERSION: "latest"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "mariadb:dev"
    image: "mariadb:dev"
    ports:
      - "3306:3306"
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/mariadb/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/mariadb/backup-volume
      
